### ISSUE TITLE
Import-From-Derivation sometimes causes `error: unexpected EOF reading a line`

### ISSUE THREAD

**Issue by Luabee** [nix-community/nix-eval-jobs#72]
I'm seeing `error: unexpected EOF reading a line` when I try to eval the same IFD expression about a hundred times.

Reproducing the problem:
```nix
with import <nixpkgs>{};
let 
    ifddrv = writeText "ifd-drv.txt" ''"hello world"'';

    test-drv = n: runCommandLocal "test-drv-${n}" {
        inherit n;
        ifd = import ifddrv;
    } ''
        echo "$ifd : $n" > $out
    '';

    n-times = n: builtins.genList (x: (toString x) + "a") n;
    op = acc: n: acc // {${n} = test-drv n;};
    targets = builtins.foldl' op {recurseForDerivations = true;} (n-times 10000);

in 
{inherit targets;}
```
- Example invocation: `nix-eval-jobs --workers 32 --gc-roots-dir $(pwd)/gcroots nix-eval-jobs-repro.nix`
- It seems to happen far more consistently when I use `--workers 32` compared to when I use `--workers 16`

This problem seems to be documented here. The blame shows that this comment has existed since the initial commit. Can anyone shed light on how this line relates to the problem as a whole?
https://github.com/nix-community/nix-eval-jobs/blob/19814b01633f539ee8d9bb80f53673bcfeb9147a/src/nix-eval-jobs.cc#L486-L488

Looks like it refers to this setting in the Nix library: https://github.com/NixOS/nix/blob/master/src/libstore/globals.hh#L201-L206

**Comment by Mic92** [comment]
`error: unexpected EOF reading a line` originates from a read line function that is used in different places in the nix code base, when nix tries to get output from child process. It might come from a build process or from a remote builder. You can see all uses of this helper here: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/NixOS/nix%24+readLine%28&patternType=literal

You might be able to find the root cause quicker by using strace on the nix-daemon with `strace -f -p $PID_OF_YOUR_NIX_DAMEON` to follow child processes as well.
The reason it might start failing at 32 workers could be memory exhaustion? But this is just a guess.

**Comment by Luabee** [comment]
Looks like this was memory exhaustion after all. I could repro the issue with any kind of targets if I cranked up the number of builds high enough. Wish there was a more descriptive error for OOM but I can close this issue.

**Comment by Luabee** [comment]
One unrelated thing I found while trying to repro this is that nix-eval-jobs refuses to evaluate attrs which have stringified number keys, such as `{"1" = drv;}`. Whereas `{"1a" = drv;}` works just fine

**Comment by Mic92** [comment]
It's a bit tricky to get this out-of-memory conditions in nix-eval-jobs since this is hidden in the nix codebase.
